pkgs <- c('tidyverse',
          'tidyr',
          'readxl',
          'curl',
          'DBI',
          'devtools',
          'data.table',
          'dbplyr',
          'extrafont',
          'gganimate',
          'ggrepel',
          'gsheet',
          'Hmisc',
          'htmltools',
          'htmlwidgets',
          'httr',
          'kableExtra',
          'knitr',
          'leaflet',
          'leaflet.extras',
          'mapproj',
          'maptools',
          'mapview',
          'markdown',
          'openssl',
          'openxlsx',
          'packrat',
          'pageviews',
          'plyr',
          'png',
          'pool',
          'purrr',
          'raster',
          'RColorBrewer',
          'Rcpp',
          'RCurl',
          'readr',
          'rgdal',
          'rjava',
          'Rmisc',
          'rmarkdown',
          'roxygen2',
          'RPosgreSQL',
          'rsconnect',
          'scales',
          'shiny',
          'shinyCAPTCHA',
          'shinydashboard',
          'shinyjs',
          'shinythemes',
          'tmap',
          'tmaptools',
          'waffle',
          'xtable',
          'yaml',
          'zoo',
          'XML',
          'jsonlite',
          'httr', 
          'rvest',
          'maptools',
          'rgeos',
          '')
pkgs <- sort(pkgs)
for(i in 1:length(pkgs)){
  this_pkg <- pkgs[i]
  if(!require(get(this_pkg))){
    message('Installing ', this_pkg)
    install.packages(this_pkg)
  } else {
    message(paste0(this_pkg, ' is already installed'))
  }
}